apiVersion: v1
kind: Secret
metadata:
  name: {{ template "launchmp-helm.fullname" . }}
type: Opaque
data:
  pc-username: {{ .Values.ntx.username | b64enc | quote }}
  pc-password: {{ .Values.ntx.password | b64enc | quote }}
  tokens: {{ .Values.ntx.tokens | b64enc | quote }}



