apiVersion: v1
kind: Secret
metadata:
  name: {{ template "launchmp-helm.fullname" . }}
type: Opaque
data:
  ntx-user: {{ .Values.ntx.user | b64enc | quote }}
  ntx-password: {{ .Values.ntx.password | b64enc | quote }}



